export function buildSeedCards() {
  const currentTime = "Сегодня";
  return [
    { id: "airpods", title: "Наушники AirPods", location: "Библиотека, 2 этаж", category: "Электроника", description: "Белые беспроводные наушники в футляре.", image: "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=85", imageAlt: "Белые беспроводные наушники", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: "12 мин назад", ratings: [] },
    { id: "student-card", title: "Студенческий билет", location: "Аудитория 204", category: "Документы", description: "Студенческий билет найден после пары.", image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=900&q=85", imageAlt: "Документы и карточки на столе", ownerName: "Анонимный пользователь", status: "Возвращено", isOwn: false, createdAt: "1 час назад", ratings: [] },
    { id: "blue-scarf", title: "Синий шарф", location: "Холл, корпус Б", category: "Одежда", description: "Синий вязаный шарф оставили на скамье.", image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=900&q=85", imageAlt: "Синий вязаный шарф", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: "Сегодня, 10:42", ratings: [] },
    { id: "clean-architecture", title: "«Чистая архитектура»", location: "Читальный зал", category: "Книги", description: "Книга оставлена на столе в читальном зале.", image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=85", imageAlt: "Книга на деревянном столе", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: "Вчера, 16:20", ratings: [] },
    { id: "usb-drive", title: "Флеш-накопитель", location: "Компьютерный класс 312", category: "Электроника", description: "Чёрная флешка на 32 ГБ.", image: "", imageAlt: "Флеш-накопитель", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "blue-notebook", title: "Синяя тетрадь", location: "Лекционный зал 1", category: "Книги", description: "Тетрадь в клетку с конспектами.", image: "", imageAlt: "Синяя тетрадь", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "black-umbrella", title: "Чёрный зонт", location: "Вход в главный корпус", category: "Другое", description: "Складной чёрный зонт с деревянной ручкой.", image: "", imageAlt: "Чёрный складной зонт", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "student-pass", title: "Пропуск кампуса", location: "Кафетерий", category: "Документы", description: "Пластиковый пропуск без видимых повреждений.", image: "", imageAlt: "Пропуск кампуса", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "gray-hoodie", title: "Серая толстовка", location: "Спортивный корпус", category: "Одежда", description: "Толстовка оставлена в раздевалке.", image: "", imageAlt: "Серая толстовка", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "wireless-mouse", title: "Беспроводная мышь", location: "Коворкинг, 1 этаж", category: "Электроника", description: "Мышь чёрного цвета, рядом нет приёмника.", image: "", imageAlt: "Беспроводная мышь", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "water-bottle", title: "Бутылка для воды", location: "Аудитория 118", category: "Другое", description: "Многоразовая прозрачная бутылка с зелёной крышкой.", image: "", imageAlt: "Бутылка для воды", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "red-gloves", title: "Красные перчатки", location: "Остановка у кампуса", category: "Одежда", description: "Пара тёплых красных перчаток.", image: "", imageAlt: "Красные перчатки", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "keys", title: "Связка ключей", location: "Столовая", category: "Другое", description: "Три ключа на металлическом кольце.", image: "", imageAlt: "Связка ключей", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "charging-case", title: "Футляр для зарядки", location: "Лаборатория 206", category: "Электроника", description: "Белый футляр для беспроводных наушников.", image: "", imageAlt: "Футляр для зарядки", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "history-book", title: "Учебник истории", location: "Читальный зал, 2 этаж", category: "Книги", description: "Учебник в мягкой обложке.", image: "", imageAlt: "Учебник истории", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] },
    { id: "glasses-case", title: "Футляр для очков", location: "Аудитория 405", category: "Другое", description: "Тёмный футляр для очков.", image: "", imageAlt: "Футляр для очков", ownerName: "Анонимный пользователь", status: "Найдено", isOwn: false, createdAt: currentTime, ratings: [] }
  ];
}
